# Site settings
title: Algo Matrix Ltd
email: algomatrix.in@gmail.com
description:  " Connect. Redifine."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://algo-matrix.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: "algo-matrix"

# Build settings
markdown: kramdown
